################################# Default configuration ###################
baseURL = "http://localhost:1313/"
title = "juuri.ai"
#theme = "Juuri.ai"
# default language
defaultContentLanguage = "fi"
# post pagination
[pagination]
pagerSize = 6
# post excerpt
summaryLength = "15"
# disqus short name
# disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language - disable French to keep only Finnish and English
disableLanguages = ["fr"]

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
# link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"
# link = "https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&display=swap"
link = "https://fonts.googleapis.com/css2?family=Open+Sans:400,700&display=swap"
# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"
[[params.plugins.js]]
link = "js/newsletter.js"

################### English Navigation ########################
[[Languages.en.menu.main]]
name = "About"
url = "#about"
weight = 1

[[Languages.en.menu.main]]
name = "Services"
url = "#services"
weight = 2

[[Languages.en.menu.main]]
name = "Portfolio"
url = "#portfolio"
weight = 3

[[Languages.en.menu.main]]
name = "Team"
url = "#team"
weight = 4

[[Languages.en.menu.main]]
name = "Pricing"
url = "#pricing"
weight = 5

[[Languages.en.menu.main]]
name = "Blog"
url = "#blog"
weight = 6

[[Languages.en.menu.main]]
name = "Contact"
url = "#contact"
weight = 7

################### Finnish Navigation ########################
# [[Languages.fi.menu.main]]
# name = "Ominaisuudet"
# url = "#about"
# weight = 1

[[Languages.fi.menu.main]]
name = "Palvelut"
url = "#palvelut"
weight = 2

# [[Languages.fi.menu.main]]
# name = "Portfolio"
# url = "#portfolio"
# weight = 3

# [[Languages.fi.menu.main]]
# name = "Perustajat"
# url = "#team"
# weight = 4

# [[Languages.fi.menu.main]]
# name = "Hinnat"
# url = "#pricing"
# weight = 5

# [[Languages.fi.menu.main]]
# name = "Uutiskirje"
# url = "#newsletter"
# weight = 6

# [[Languages.fi.menu.main]]
#  name = "Blogi"
#  url = "#blog"
#  weight = 7

[[Languages.fi.menu.main]]
name = "Ota yhteyttä"
url = "#otayhteytta"
weight = 8

############################# Default Parameters ##########################
[params]
enable = true
logo = "images/juuri-ai-logo-rgb.svg"
# Meta data
description = "Yhdistämme tekoälyn ja inhimillisen markkinoinnin tulokselliseksi kokonaisuudeksi. Vapauta kasvu – ota AI osaksi liiketoimintaasi jo tänään."
# og kuva
og_image = "images/juuri_ai_og_1200x628.jpg"
author = "Juuri.ai"
# Google Analytics
google_analytics_id = "G-SFX2TLQLTE"
# post share
post_share = true
calendar_url = "https://calendar.google.com/calendar/u/0?cid=Y182NTcxODRkYjgwNjI4MmYxMDIzOTBmMWFlZjRkNGNmMGFiODU3NGM0MDZiMWViMzBmNTc4NjM0YmM5MjUxMjVhQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20"
calendar_text = "Varaa Aika"
blogBannerTitle = "Juuri.ai artikkelit"
blogBannerSubtitle = "Your Subtitle Here"

######## Site Fonts ###########
#sitefontlink = "https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700&display=swap"
#sitefont = "\"Open Sans\", sans-serif"
# Popular font combinations you can copy/paste:

# Open Sans (current - clean, professional)
# sitefontlink = "https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,400;0,700;1,400&display=swap"
# sitefont = "Open Sans"

# Inter (modern interface font - excellent for digital products)
#sitefontlink = "https://fonts.googleapis.com/css2?family=Inter:ital,wght@0,400;0,700;1,400&display=swap"
#sitefont = "Inter"

# Poppins (persoonallisempi mutta trendikäs - friendly, rounded)
# sitefontlink = "https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,700;1,400&display=swap"
# sitefont = "Poppins"

# Source Sans Pro (Adobe's humanist sans-serif)
# sitefontlink = "https://fonts.googleapis.com/css2?family=Source+Sans+3:ital,wght@0,400;0,700;1,400&display=swap"
# sitefont = "Source Sans 3"

# Nunito Sans (persoonallinen - warm, friendly personality)
# sitefontlink = "https://fonts.googleapis.com/css2?family=Nunito+Sans:ital,wght@0,400;0,700;1,400&display=swap"
# sitefont = "Nunito Sans"

# Manrope (modern geometric - excellent readability)
# sitefontlink = "https://fonts.googleapis.com/css2?family=Manrope:wght@400;700&display=swap"
# sitefont = "Manrope"

# DM Sans (versatile - perfect for UI and content)
sitefontlink = "https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,700;1,400&display=swap"
sitefont = "DM Sans"

# System fonts (fastest - no web loading)
# sitefontlink = ""
# sitefont = "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif"

############################# Siteset Colors Configuration ##########################
# Choose siteset colors from available options: saaristo, kaste, korpi, hiekka, loimu, viima, verso, kipina, apila, helle, sahakka, ruska, harmonia, tuli, yo, tiikeri, syksy, neon, pastilli, pinkki, onecolor, terra, jklav1, jklav2
siteset = "korpi"

[params.sections]
    [params.sections.banner]
      enable = true
    [params.sections.team]
      enable = true
    [params.sections.services]
      enable = true
    [params.sections.feature]
      enable = false
    [params.sections.about]
      enable = true
    [params.sections.cta]
      enable = false
    [params.sections.skill]
      enable = false
    [params.sections.portfolio]
      enable = false
    [params.sections.funfacts]
      enable = false
    [params.sections.comparison]
      enable = true
    [params.sections.pricing]
      enable = false
    [params.sections.testimonial]
      enable = false
    [params.sections.blog]
      enable = true
    [params.sections.faq]
      enable = true
    [params.sections.newsletter]
      enable = false
    [params.sections.contact]
      enable = true
    [params.sections.gallery]
      enable = false
    [params.sections.map]
      enable = false
    [params.sections.footer]
      enable = true



# Section-specific sectionset configuration
# Each section can use different sectionsets within the same siteset
# Available sectionsets: lightset, neutralset, darkset, coloriset
[params.sectionsets]
  banner = "lightset"        # Hero/banner section
  about = "darkset"        # About section
  services = "neutralset"   # Services section
  service_pages = "lightset"  # Individual service pages 
  service = "lightset"   # Service section
  portfolio = "lightset"    # Portfolio section
  team = "lightset"        # Team section
  pricing = "lightset"    # Pricing section
  blog = "coloriset"         # Blog section
  contact = "lightset"       # Contact section
  comparison = "lightset" # Comparison section
  faq = "neutralset"         # FAQ section
  funfacts = "lightset"   # Funfacts section
  testimonial = "coloriset" # Testimonial section
  cta = "coloriset"          # Call-to-action section
  newsletter = "coloriset"   # Newsletter section 
  feature = "coloriset"   # ikoninostot section 
  article = "coloriset"   # blogit
  gallery = "lightset"   # gridilistaus tuotteista
  services-hero = "lightset"   # Services hero single sivuilla (tuotesivut)
  navigation = "neutralset"   # navbar
  main_text = "lightset"   # service-single sivun ensimmäinen palvelukuvaus
  packages = "neutralset"       # services singlesivun main teksti osio
  expert = "darkset"     # singlesivulla kouluttaja osio
  benefits = "darkset"    # ikonibanneri singlesivulla
  service_faq = "neutralset" # services single sivun faq
  privacy = "neutralset" # 


# preloader
[params.preloader]
enable = false
preloader = "/images/juuri-ai-logo-rgb.svg"

# cookies
[params.cookies]
enable = false
expire_days = 2

# google map
[params.map]
enable = false
gmap_api = "hthttps://calendar.google.com/calendar/u/0?cid=Y182NTcxODRkYjgwNjI4MmYxMDIzOTBmMWFlZjRkNGNmMGFiODU3NGM0MDZiMWViMzBmNTc4NjM0YmM5MjUxMjVhQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20"
map_latitude = "60.976896"
map_longitude = "24.467889"
map_marker = "images/marker.png"

# Navigation button
[params.nav_button]
enable = true
label = "Varaa aika"
link = "https://calendar.google.com/calendar/embed?src=c_657184db806282f102390f1aef4d4cf0ab8574c406b1eb30f578634bc925125a%40group.calendar.google.com&ctz=Europe%2FHelsinki"

############################# Button System Configuration ##########################
# Yksinkertainen button määrittely - värimäärittelyjen mukaisesti
[params.buttons]
  # Button style - ghost tai fill
  # "ghost" = läpinäkyvä pohja, täytetty hover
  # "fill"  = täytetty pohja, läpinäkyvä hover
  style = "ghost"
  
  # Button corner style
  # "square"  = 0px (suorakulmainen)
  # "rounded" = 8px (lievästi pyöristetty)  
  # "round"   = 50px (täysin pyöreä)
  corners = "round"
  
  # Valinnainen mukautettu pyöristys (ohittaa corners asetuksen)
  # custom_radius = "0px"

############################# social icons ##########################
[[params.social]]
enable = true
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
enable = true
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
enable = false
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
enable = true
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
enable = false
icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
enable = false
icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
link = "#"


################################ English Language ########################
[Languages.en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
copyright = "Copyright &copy; 2025 juuri.ai. All rights reserved."

################################ Finnish Language ########################
[Languages.fi]
languageName = "Suomi"
languageCode = "fi-fi"
contentDir = "content/finnish"
weight = 2
home = "Koti"
copyright = "Copyright &copy; 2025 juuri.ai. Kaikki oikeudet pidätetään."

